# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import enum
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow,input_data):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 150, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        
        

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.table_ui(MainWindow,input_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def table_ui(self, MainWindow,input_data):
        

        self.tableWidget.setRowCount(len(input_data))
        self.tableWidget.setColumnCount(2)
        
        for count,value in enumerate(input_data):
            
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(count, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(count, item)
            
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count, 1, item)


        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Seatrac"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "data"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "value"))

        for count,value in enumerate(input_data):
            item = self.tableWidget.verticalHeaderItem(count)
            item.setText(_translate("MainWindow",str(count)))

            item = self.tableWidget.item(count, 0)
            item.setText(_translate("MainWindow",value))

            item = self.tableWidget.item(count, 1)
            item.setText(_translate("MainWindow", str(input_data[value])))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()

    name={"Nikhil" : 1, "Akshat" : 2, "Akash" : 3,"Agfkash" : 4}

    ui.setupUi(MainWindow,name)
    MainWindow.show()
    sys.exit(app.exec_())